name: uwvm-llvm-cross-compile-test

on:
  pull_request:
    branches: ["master", "dev"]
  push:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
            xmake-version: branch@dev
      - name: Prepare
        run: |
          wget https://github.com/24bit-xjkp/toolchains/releases/download/llvm19/x86_64-linux-gnu-clang19.tar.xz
          tar xf x86_64-linux-gnu-clang19.tar.xz
          wget https://github.com/24bit-xjkp/toolchains/releases/download/llvm19/sysroot.tar.xz
          tar xf sysroot.tar.xz
      - name: Tests-x86_64-inux-gnu
        run: |
          xmake f -p linux -a x86_64 -m debug --static=n --use-llvm=y --llvm-target=x86_64-linux-gnu --sysroot=`pwd`/sysroot/x86_64-linux-gnu --sdk=`pwd`/x86_64-linux-gnu-clang19/
          xmake
      - name: Tests-i386-inux-gnu
        run: |
          xmake f -p linux -a i386 -m debug --static=n --use-llvm=y --llvm-target=i386-linux-gnu --sysroot=`pwd`/sysroot/i686-linux-gnu --sdk=`pwd`/x86_64-linux-gnu-clang19/
          xmake
      - name: Tests-aarch64-inux-gnu
        run: |
          xmake f -p linux -a aarch64 -m debug --static=n --use-llvm=y --llvm-target=aarch64-linux-gnu --sysroot=`pwd`/sysroot/aarch64-linux-gnu --sdk=`pwd`/x86_64-linux-gnu-clang19/
          xmake
      - name: Tests-loongarch64-inux-gnu
        run: |
          xmake f -p linux -a loongarch64 -m debug --static=n --use-llvm=y --llvm-target=loongarch64-linux-gnu --sysroot=`pwd`/sysroot/loongarch64-linux-gnu --sdk=`pwd`/x86_64-linux-gnu-clang19/
          xmake
      - name: Tests-riscv64-inux-gnu
        run: |
          xmake f -p linux -a riscv64 -m debug --static=n --use-llvm=y --llvm-target=riscv64-linux-gnu --sysroot=`pwd`/sysroot/riscv64-linux-gnu --sdk=`pwd`/x86_64-linux-gnu-clang19/
          xmake
      - name: Tests-x86_64-windows-gnu
        run: |
          xmake f -p mingw -a x86_64 -m debug --static=n --use-llvm=y --llvm-target=x86_64-windows-gnu --sysroot=`pwd`/sysroot/x86_64-w64-mingw32 --sdk=`pwd`/x86_64-linux-gnu-clang19/
          xmake
      - name: Tests-i386-windows-gnu
        run: |
          xmake f -p mingw -a i386 -m debug --static=n --use-llvm=y --llvm-target=i386-windows-gnu --sysroot=`pwd`/sysroot/i686-w64-mingw32 --sdk=`pwd`/x86_64-linux-gnu-clang19/
          xmake
