name: uwvm-build

on:
  pull_request:
    branches: ["master", "dev"]
  push:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
  
      - name: Build-Default-x86_64-linux-gnu
        run: |
          xmake clean
          xmake f --clean
          xmake f -p linux -a x86_64 -m debug --static=n
          xmake -v
      - name: Test-Default-x86_64-linux-gnu
        run: |
          xmake run uwvm --version
          xmake install -o `pwd`/uwvm-install/
      - name: Build-UWVM-TEST-x86_64-linux-gnu
        run: |
          xmake clean
          xmake f --clean
          xmake f -p linux -a x86_64 -m debug --static=n --uwvm-test=y --policies=build.sanitizer.address
          xmake -v
      - name: Test-UWVM-TEST-x86_64-linux-gnu
        run: |
          xmake run uwvm
      - name: Prepare-Default-wasm32-wasip1
        run: |
          wget https://github.com/MacroModel/gcc-release/releases/download/llvm6/x86_64-linux-gnu-2.17-native-llvm.tar.xz
          tar -xf x86_64-linux-gnu-2.17-native-llvm.tar.xz
          wget https://github.com/trcrsired/llvm-releases/releases/download/llvm20-20240723/wasm-sysroots.tar.xz
          tar -xf wasm-sysroots.tar.xz
          `pwd`/x86_64-linux-gnu-2.17-native-llvm/bin/clang -v
      - name: Build-Default-wasm32-wasip1
        run: |
          xmake f -p wasm-wasip1 -a wasm32 -m debug --use-llvm=y --sdk=`pwd`/x86_64-linux-gnu-2.17-native-llvm/ --sysroot=`pwd`/wasm-sysroots/wasm-sysroot/wasm32-wasip1/
          xmake -v
          xmake install -o `pwd`/uwvm-install/
      - name: Test-Default-wasm32-wasip1
        run: |
          `pwd`/uwvm-install/bin/uwvm -r `pwd`/uwvm-install/bin/uwvm.wasm -v
          
