name: uwvm-build

on:
  pull_request:
    branches: ["master", "dev"]
  push:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
  
      - name: Build-Default-x86_64-linux-gnu
        run: |
          xmake clean
          xmake f --clean
          xmake f -p linux -a x86_64 -m debug --static=n
          xmake -v
      - name: Test-Default-x86_64-linux-gnu
        run: |
          xmake run uwvm --version
