name: uwvm-build

on:
  pull_request:
    branches: ["master", "dev"]
  push:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
      - name: Prepare
        run: |
          wget https://github.com/trcrsired/gcc-releases/releases/download/2024-04-30-x86_64-generic-linux-gnu/x86_64-generic-linux-gnu.tar.xz
          tar xf x86_64-generic-linux-gnu.tar.xz
          rsync -a x86_64-generic-linux-gnu/runtimes/* x86_64-generic-linux-gnu/
      - name: Tests-x86_64-inux-gnu
        run: |
          xmake f -p linux -a x86_64 -m debug --static=n --sdk=`pwd`/x86_64-generic-linux-gnu/
          xmake
